name: Check Current Directory

on:
  push:
    branches:
      - main

jobs:
  check_directory:
    runs-on: ubuntu-latest
    steps:
      - name: Check Current Directory
        run: |
          pwd
